CREATE DATABASE IF NOT EXISTS MONEYSNAP;
USE MONEYSNAP;

CREATE TABLE Users (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(255),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    DELETED_AT DATETIME
);

CREATE TABLE TransactionCategories (
    TRANSACTION_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    DELETED_AT DATETIME
);

CREATE TABLE Transactions (
    TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    TRANSACTION_CATEGORY_ID INT,
    AMOUNT DECIMAL(12,2),
    DESCRIPTION TEXT,
    TYPE VARCHAR(50),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (TRANSACTION_CATEGORY_ID) REFERENCES TransactionCategories(TRANSACTION_CATEGORY_ID)
);

CREATE TABLE Savings (
    SAVING_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTION_ID INT,
    NAME VARCHAR(100),
    CURRENT_BALANCE DECIMAL(12,2),
    DEADLINE DATE,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    DELETED_AT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES Transactions(TRANSACTION_ID)
);

CREATE TABLE Expenses (
    EXPENSE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTION_ID INT,
    NAME VARCHAR(100),
    CURRENT_BALANCE DECIMAL(12,2),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    DELETED_AT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES Transactions(TRANSACTION_ID)
);

CREATE TABLE Incomes (
    INCOME_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTION_ID INT,
    NAME VARCHAR(100),
    CURRENT_BALANCE DECIMAL(12,2),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    DELETED_AT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES Transactions(TRANSACTION_ID)
);
